spring:
  application:
    name: MusicPlay
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
misc:
  dataPath: data.json
storage:
  accessKey: GK07f3744cb06e129ce707975e
  secretKey: 31cf4727b4601aa5e3c9116f5d76112dff2b8391e04e2dd6354b5c5fca10cd27
  regionName: garage
  bucketName: "music-play-playlist"
  host: http://localhost:3900
