spring:
  application:
    name: MusicPlay
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
search:
  url: ${SEARCH_URL}
  core: ${SEARCH_CORE}
storage:
  host: ${STORAGE_HOST}
  regionName: ${STORAGE_REGION_NAME}
  bucketName: ${STORAGE_BUCKET_NAME}
  accessKey: ${STORAGE_ACCESS_KEY}
  secretKey: ${STORAGE_SECRET_KEY}
